spring.application.name=VogueNest
server.port=${PORT:10000}


spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

app.admin.email=${VOGUENEST_ADMIN_EMAIL:admin@voguenest.com}
app.admin.password=${VOGUENEST_ADMIN_PASSWORD:admin123}

logging.level.org.springframework.web=DEBUG