spring.application.name=VogueNest
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/wardrobe_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Osheenkhan@1031}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
app.admin.email=${VOGUENEST_ADMIN_EMAIL:admin@voguenest.com}
app.admin.password=${VOGUENEST_ADMIN_PASSWORD:admin123}
logging.level.org.springframework.web=DEBUG