# MySQL Datasource Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://vogue-nest-db-osheenk66-39a0.j.aivencloud.com:18856/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Driver and Dialect for MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Auto-update database tables on deploy
spring.jpa.hibernate.ddl-auto=update

# App properties
app.admin.email=${APP_ADMIN_EMAIL:admin@voguenest.com}